version: '3.1'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: elasticsearch
    networks:
      - elk
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
    #volumes:
    #  - ./config/elasticsearch:/usr/share/elasticsearch/config
  logstash:
    image: docker.elastic.co/logstash/logstash:7.13.1
    container_name: logstash
    #volumes:
    # - ./pipeline:/usr/share/logstash/pipeline
    networks:
      - elk
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.1
    container_name: kibana
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - elk
    depends_on:
      - elasticsearch
    volumes:
      - ./config/kibana:/usr/share/kibana/config

networks:
  elk:
